# Shared words used by both client and server.
# Keeping these in one file prevents spelling mistakes in JSON messages.

# Message types.
JOIN = "JOIN"
PLAYER_LIST = "PLAYER_LIST"
SELECT_OPPONENT = "SELECT_OPPONENT"
MATCH_RESPONSE = "MATCH_RESPONSE"
SNAKE_CONFIG = "SNAKE_CONFIG"
MOVE = "MOVE"
GAME_STATE = "GAME_STATE"
GAME_OVER = "GAME_OVER"
READY = "READY"
DISCONNECT = "DISCONNECT"
ERROR = "ERROR"

# Snake directions.
UP = "UP"
DOWN = "DOWN"
LEFT = "LEFT"
RIGHT = "RIGHT"

# JSON field names.
FIELD_TYPE = "TYPE"
FIELD_USERNAME = "USERNAME"
FIELD_GAME_ID = "GAME_ID"
FIELD_DIRECTION = "DIRECTION"
FIELD_PLAYERS = "PLAYERS"
FIELD_OPPONENT = "OPPONENT"
FIELD_BOARD = "BOARD"
FIELD_FOOD = "FOOD"
FIELD_OBSTACLES = "OBSTACLES"
FIELD_SCORE = "SCORE"
FIELD_WINNER = "WINNER"
FIELD_MESSAGE = "MESSAGE"
FIELD_COLOR = "COLOR"
FIELD_HEALTH = "HEALTH"
FIELD_PLAYER_ID = "PLAYER_ID"
FIELD_STATUS = "STATUS"
FIELD_PLAYERS_DATA = "PLAYERS_DATA"
FIELD_TIME_LEFT = "TIME_LEFT"
FIELD_SPECTATORS = "SPECTATORS"
FIELD_DECISION = "DECISION"

# General status values.
STATUS_OK = "OK"
STATUS_FAIL = "FAIL"
STATUS_INVALID = "INVALID"
STATUS_ACCEPT = "ACCEPT"
STATUS_REJECT = "REJECT"
STATUS_PENDING = "PENDING"

# Server-side player states.
PLAYER_STATUS_ONLINE = "ONLINE"
PLAYER_STATUS_OFFLINE = "OFFLINE"
PLAYER_STATUS_IN_GAME = "IN_GAME"
PLAYER_STATUS_WAITING = "WAITING"
PLAYER_STATUS_PENDING = "PENDING"
